name: Sphinx docs to gh-pages

on:
  push:
    branches:
      - main

jobs:
  sphinx_docs_to_gh-pages:
    runs-on: ubuntu-latest
    name: Sphinx docs to gh-pages

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.9  # https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
          cache: pip

      - uses: abatilo/actions-poetry@v2.2.0

      - name: Build documentation
        run: |
          echo "installing the pip dependencies..."
          pip install sphinx-rtd-theme sphinx-autodocgen
          mkdir gh-pages
          touch gh-pages/.nojekyll
          echo "building the docummentation pages..."
          cd docs
          poetry run sphinx-build -b html . _build
          cp -r _build/* ../gh-pages

      - name: Deploy documentation
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: gh-pages
